### ISSUE TITLE
Camera View

### ISSUE THREAD

**Issue by andrew-snape** [KieraDOG/homebridge-cgd-garage-door#5]
Hi, 
I was wondering whether its possible to add the camera feed for the door which is accessible on port 88 of the IP/host name of the camera?

**Comment by KieraDOG** [comment]
Hey Andrew,

I've updated the README to include instructions on how to integrate the door camera into Homebridge using the [Homebridge Camera FFmpeg](https://github.com/homebridge-plugins/homebridge-camera-ffmpeg) plugin. Let me know if you have any questions or need further assistance!

https://github.com/KieraDOG/homebridge-cgd-garage-door?tab=readme-ov-file#camera-integration
